export default function TermsPage() {
  return (
    <div className="pt-28 pb-20">
      <div className="max-w-3xl mx-auto px-6">
        <h1 className="text-4xl font-bold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-muted mb-10">Last updated: July 19, 2026</p>

        <div className="prose prose-lg text-muted space-y-8">
          <section>
            <h2 className="text-xl font-semibold text-ink">1. Acceptance of Terms</h2>
            <p>
              By accessing or using PodcastMaker, you agree to be bound by these Terms 
              of Service. If you do not agree, do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">2. Your Content</h2>
            <p>
              You retain ownership of all content you create using PodcastMaker. 
              We do not claim any rights over your podcasts, scripts, or audio files.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">3. Acceptable Use</h2>
            <p>
              You may not use PodcastMaker to generate content that is illegal, 
              harmful, abusive, or violates the rights of others. You are responsible 
              for the content you create.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">4. AI-Generated Content</h2>
            <p>
              Content generated by AI may not always be accurate. You should review 
              and verify all generated content before publishing or sharing.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">5. Account Termination</h2>
            <p>
              You may delete your account at any time. We reserve the right to 
              suspend or terminate accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-ink">6. Limitation of Liability</h2>
            <p>
              PodcastMaker is provided "as is" without warranties. We are not liable 
              for any damages arising from your use of the service.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
